# Generated by Django 6.0.2 on 2026-02-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('adderss', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Teachers_image')),
            ],
        ),
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Assignments',
        ),
    ]
